name: CI
on: 
  push: 
    branches: 
      - 'develop'
      - 'release'
permissions: 
  contents: read
  packages: write
jobs:
  push: 
    runs-on: ubuntu-latest
    steps: 
      - name: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: registry-login
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: build 
        id: build 
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository }}:${{ github.sha }}